export const mentors = [
  {
    id: 1,
    name: "Dr. Jay Patel",
    img: "/images/team/jay_patel.jpg",
    linkedln: "https://www.linkedin.com/in/jay-patel-77795910b/",
    department: "CEO",
    position: "Founder & CEO",
    about:
      "Jay Patel is an MD in Medicine and a Philanthropist having supported many initiatives across various institutions and geographies. Being a visionary evangelist and consensus team-builder, he set foot within entrepreneurship and founded several companies to help businesses reach their true potential. His commercial and business acumen provides invaluable leadership to all his projects.",
    qualifications: ["Doctor of Medicine- MD"],
    experience: [
      "Founder of multiple startups including - CREMTex, TECH196 and LCT360",
    ],
    areas_of_expertise: [
      "Innovations",
      "Investments",
      "Global Visionary",
      "Entrepreneurship",
    ],
  },
  {
    id: 2,
    name: "Jay Hao",
    img: "/images/team/jay_hao.png",
    linkedln: "https://www.linkedin.com/in/jayhaookex/",
    department: "Advisor",
    position: "Entrepreneur & Advisor",
    about:
      "As the CEO of OKEx, a world-leading cryptocurrency and Bitcoin exchange that provides hundreds of trading pairs for spot and derivatives. Jay Hao is a firm believer in the potential of blockchain and foresees a future when this technology eliminates all transaction barriers, achieves unparalleled efficiency, and leads to substantial improvements in the global economic system.",
    qualifications: ["MSEE", "Electrical Engineering"],
    experience: [
      "12 years CEO",
      "8 years Chairperson",
      "1 year Project management",
      "1 year Vice President of Engineering",
    ],
    areas_of_expertise: [
      "Leadership",
      "Blockchain",
      "Public Speaking",
      "Product Development",
      "Cryptocurrency",
      "Advisor",
    ],
  },
  {
    id: 3,
    name: "Don Janssen",
    img: "/images/team/don_jassen.png",
    linkedln: "https://www.linkedin.com/in/don-janssen-081095a/",
    department: "advisor",
    position: "Real Estate Advisor",
    about:
      "Don is Executive Vice President of PCD with responsibility for commercial land sales, ground leases, and office leasing. Since joining the company in 1980, Mr. Janssen has been involved in commercial development transactions representing more than 3,000 acres and 5,000,000 square feet. In addition, Janssen is a past president of the Sugar Land Rotary Club, Vice Chairman of the Fort Bend Baptist Academy Board of Trustees and has served on many civic organization committees.",
    qualifications: [],
    experience: ["40 years of experience in Real Estate Management"],
    areas_of_expertise: [
      "Commercial land sales",
      "Ground leases",
      "Office leasing",
    ],
  },
  // {
  //   id: 4,
  //   name: "Mahesh Sashital",
  //   img: "/images/team/mahesh_sashital.png",
  //   linkedln: "https://www.linkedin.com/in/maheshsashital/",
  //   department: "Technology",
  //   position: "Technology Leader",
  //   about:
  //     'Mahesh Sashital is a technology executive with over 20 years of software engineering and product management experience, developing, leading, and launching projects and products at Fortune 500 companies as well as startups. His expertise includes next-gen technologies such as Blockchain, IoT, RPA and AI/ML, in addition to the years of "traditional" mainstream technologies such as Java, Oracle and Web Services. Mahesh also has extensive experience working at companies such as JPMorgan, Ford, and Chrysler, and has a thorough understanding of the technology practices at such large companies.',
  //   qualifications: [
  //     "Certified Scrum Product Owner (CSPO)",
  //     "Bachelor of Engineering",
  //     "Master of Business Administration",
  //   ],
  //   experience: [
  //     "5 years President",
  //     "3 years Founder",
  //     "1 year Mentor and Judge",
  //     "1 year Director of Technology",
  //   ],
  //   areas_of_expertise: [
  //     "Technology",
  //     "Blockchain",
  //     "FinTech and Strategy",
  //     "Product management",
  //     "T Strategy",
  //     "Business strategy",
  //     "SQL",
  //     "Blockchain",
  //     "Robotic process automation",
  //   ],
  // },
  {
    id: 5,
    name: "Anil Ali",
    img: "/images/team/anil_ali.png",
    linkedln: "https://www.linkedin.com/in/anil-ali-a076364/",
    department: "Attorney",
    position: "Attorney",
    about:
      "Anil Ali is a Houston native that has been practicing law since 2008. Anil went to law school at the South Texas College of Law. While in law school he reviewed the work of scientists to parse their technical background to help prepare their case before the United States government in obtaining a National Interest Waiver. Registered to practice before the U.S. Patent and Trademark Office and with a diverse background and ability to tackle any scientific field, Anil is ready to help you with your intellectual property (IP) goals that may be patents, trademarks, copyrights, or business-related to those.",
    qualifications: ["Doctor of Law (JD)"],
    experience: ["10 years CEO", "3 years Attorney"],
    areas_of_expertise: [
      "Commercial litigation",
      "Civil litigation",
      "Startups",
      "Intellectual property",
      "Mergers and Acquisitions",
      "Corporate Law",
    ],
  },
  // {
  //   id: 6,
  //   name: "Neeraj Satija",
  //   img: "/images/team/neeraj_satija.png",
  //   linkedln: "https://www.linkedin.com/in/neerajsatija/",
  //   department: "technology",
  //   position: "CTO",
  //   about:
  //     "With over 21 years’ of experience in the IT industry during which Neeraj had various IT leadership positions with organizations like Concordus Apps, 2degrees Mobile Limited (2degrees), IBM and HP-EDS/Telecom NZ. Neeraj also has extensive Telecommunications domain knowledge - having played a key role in the set-up, launch and growth of two start-up Telco’s (2degrees Mobile Ltd. and Mobily, Saudi Arabia). Neeraj also has spent five years working for an established, dominant Telco (Telecom New Zealand).",
  //   qualifications: [
  //     "Master of Business Administration",
  //     "Bachelor of Technology, Computer Science",
  //   ],
  //   experience: [
  //     "3 years Enterprise Architect",
  //     "8 years Software Development Manager",
  //     "5 years CTO",
  //     "5 years CEO",
  //   ],
  //   areas_of_expertise: [
  //     "Telecom BSS",
  //     "Business transformation",
  //     "Program management",
  //     "Software development",
  //     "Business Analysis",
  //     "Solution architecture",
  //     "Vendor management",
  //     "Software project management",
  //   ],
  // },
  {
    id: 7,
    name: "Frank Monachelli",
    img: "/images/team/frank_monachelli.png",
    linkedln: "https://www.linkedin.com/in/frankmonachelli/",
    department: "advisor",
    position: "Advisor",
    about:
      "Frank is a CFO / Finance Director with experience in banking, retail, and manufacturing industries. He has skills in budgeting, forecasting, strategic planning, activity-based costing, financial accounting, financial modeling, pricing, derivatives, Sarbanes-Oxley, segment analysis and all other areas of corporate finance. Not only is he a strong finance professional with experience leading simultaneous teams in multiple states and proactively supporting business partners but also has an extensive work history in complex and highly matrixed organizations.",
    qualifications: [
      "Corporate management BBVA",
      "BA economic",
      "Creating corporate advantag",
      "CFO excellence",
      "MBA Finance",
    ],
    experience: [
      "3 years Board member",
      "9 years Texas cabinet",
      "2 years Finance Manager",
      "18 years Finance Director",
    ],
    areas_of_expertise: [
      "Banking",
      "Credit analysis",
      "Financial modelling",
      "Derivatives",
      "Mergers and Acquisitions",
      "Portfolio Management",
      "Financial risk management",
      "Investment banking",
      "Treasury management",
    ],
  },
  {
    id: 8,
    name: "Andy Chopra",
    img: "/images/team/andy_chopra.png",
    linkedln: "https://www.linkedin.com/in/andy-chopra-phd-00a1a84/",
    position: "Research & Outreach",
    department: "research & outreach",
    about:
      "Andy has International Emerging Technologies research experience that spans over 16 years with global IT companies along with a deep experience in working with International Banking, Insurance and Technology clients in over 7 countries. In his current role, he advises startups on business plan, market/competitor analysis, technology research and benchmarking studies, product analysis, marketing resources/ techniques, elevator pitch, investor deck presentations, funding strategies and resources.",
    qualifications: [
      "MBA",
      "International management",
      "Doctor of Philosophy (Ph.D.)",
      "MIT Fintech Future Commerce",
    ],
    experience: [
      "1.5 years as Head of Research & Outreach",
      "3 years Co-founder and partner",
      "5 years Director of research & marketing",
      "5.5 years Senior Manager",
      "2 years Economist",
    ],
    areas_of_expertise: [
      "Business research",
      "Business development",
      "Project management",
      "Data analytics",
      "Marketing",
      "Business strategy",
      "Financial research",
      "Business transformation, market research and strategic planning",
    ],
  },
  {
    id: 9,
    name: "Deepak Sharma",
    img: "/images/team/deepak_sharma.png",
    linkedln: "https://www.linkedin.com/in/deepak-sharma-4b21a1181/",
    department: "investment",
    position: "Invesments",
    about:
      "Deepak founded many companies and exited many successfully. He overlooks strategy and its implementation for Generation Rise. He is serial entrepreneur and has been involved with multiple global ventures. Deepak brings 20 plus years of business and technology expertise across industry domains while he is an avid working enthusiast in creating disruptive technology and businesses in the field of assets and securities. Deepak has earned MS in Computer Science from Michigan State, USA and BS in Computer Engineering. He has also received Bachelor in Legislative Law, Diploma in UN International financing.",
    qualifications: [
      "Bachelor of Engineering",
      "Master's degree in Management Information Systems",
      "Master’s degree in Cyber Law",
      "Master's degree Business Administration and Management",
    ],
    experience: [
      "2 years Senior Software Engineer",
      "19 years Founder",
      "5 years Entrepreneur",
    ],
    areas_of_expertise: [
      "Business Administration and Management",
      "Entrepreneurship",
    ],
  },
  {
    id: 10,
    name: "Harish Mamtani",
    img: "/images/team/harish_mamtani.png",
    linkedln: "https://www.linkedin.com/in/harishmamtani/",
    department: "investment",
    position: "Investments",
    about:
      "Harish has been dedicated to building Recordent. Additionally, he is an advisor for building high-quality private schools in Hyderabad, India. He has previously advised high net worth clients and family offices on investments since 1998. Not only has he invested in equities, hedge funds (direct and fund of funds), private equity, real estate (domestic and international) but also managed direct investments in the technology, healthcare, and real estate sectors.",
    qualifications: [
      "IMBA",
      "Master's in International Business",
      "BS Accounting & Finance",
    ],
    experience: [
      "2 years Financial advisor",
      "5 years Vice President",
      "2 years Investment advisor",
      "6 years Board of Director",
      "4 years Vice chairperson",
      "14 years Managing Director",
      "8 years Founder and Board member",
    ],
    areas_of_expertise: [
      "Entrepreneurship",
      "Investments",
      "Portfolio management",
      "Venture capital",
      "Hedge funds",
      "Financial modeling",
      "Asset allocation",
      "Real estate",
      "Equities",
    ],
  },
  {
    id: 11,
    name: "Daniel Sloan",
    img: "/images/team/daniel_sloan.png",
    linkedln: "https://www.linkedin.com/in/sloandaniel/",
    department: "Advisor",
    position: "Blockchain/AI",
    about:
      "Daniel has been in the Information Technology industry since 1995 and has built multiple businesses over his 23-year career.  BlockchainSaw, LLC is Daniel’s most recent venture, and he is focused on helping companies understand the value that Blockchain can bring.  Daniel and his team work closely with companies to put together a strategy that will enable them to integrate Blockchain or build new custom applications to realize its value. ”Once a Marine, always a Marine... the principles and lessons I learned as a Marine have helped me throughout my life",
    qualifications: ["BS, Business Administration"],
    experience: [
      "VP for 8 years",
      "Founder for 14 years",
      "4 years CEO, 5 years Advisor",
      "4 years Board member",
    ],
    areas_of_expertise: [
      "Business development",
      "Start-ups",
      "Blockchain",
      "DeFi",
      "Investment",
      "Cryptocurrency",
      "NFTs",
      "Business strategy",
      "Strategic planning",
      "Entrepreneurship",
      "Marketing",
      "Consulting",
      "Software development",
    ],
  },
  {
    id: 12,
    name: "Carla Marie Williams",
    img: "/images/team/carla_marie.png",
    linkedln: "",
    department: "Business Development Superstar",
    position: "Business Development Superstar",
    about:
      "At 13 years old, Carla Marie performed an original speech on the stage of The Potter's House- one of the largest churches in America. By 17 she founded her first teen lead organization, headquartered out of her parents home and at the ripe age of 24- she started a coaching business that trained on building positive, inclusive and revolutionary team cultures. Carla Marie believes in creating movements out of brands, believers out of people, and transcendental game changers in the business world. With years of organizational leadership, entrepreneurship, business development and marketing & sales experience- she'll show innovators how to BE the unicorns they want their technology to become.",
    qualifications: ["BS, Business Administration"],
    experience: [],
    areas_of_expertise: [
      "Organizational Leadership",
      "Entrepreneurship",
      "Business Development",
      "Marketing",
      "Sales",
    ],
  },
];
